In [14]:
import warnings
warnings.filterwarnings("ignore")

# Sklearn的机器学习框架-分类问题

## 1. 数据导入

In [15]:
import pandas as pd
from sklearn.datasets import load_iris,load_boston,load_breast_cancer,load_digits,load_wine
# load_iris ： 鸢尾花数据集，适合做分类， 4个特征列 花瓣长..花萼宽   1个目标 花类别  分类问题  
# load_boston : boston房价数据集，适合做回归：　14个和房子相关的特征   1个目标 房价  回归问题

iris = load_iris()
iris.keys()  # 导入的是一个字典，包含data， target等等

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

## 2. 选取特征和目标

In [16]:
X = iris.data  # numpy 数组 包含特征数据 X 
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
y = iris.target # numpy数组 包含目标数据 y 也就是每朵花的类别
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
print("X特征：",X.shape) # 150行 ， 4列， 150多花，每朵花有4个特征
print("y目标：",y.shape) # 150行 ， 1列， 150朵花的类别

X特征： (150, 4)
y目标： (150,)


## 3. 划分训练和测试集

In [19]:
from sklearn.model_selection import train_test_split  

X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                 test_size=0.2,train_size=0.8, # 只需要指定一个，另一个就是剩下的
                                                 shuffle=True, # 是否打乱数据
                                                 stratify=None # 按类别比例取值
                                                )

In [20]:
print("X训练特征：",X_train.shape)
print("y训练目标：",y_train.shape)
print("X测试特征：",X_test.shape) 
print("y测试目标：",y_test.shape) 

X训练特征： (120, 4)
y训练目标： (120,)
X测试特征： (30, 4)
y测试目标： (30,)


## 4. 选择算法构造模型

In [21]:
# 分类问题：
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor  # KNN K-nearest-neighbors K近邻
# Classifier是分类器
# Regressor是回归器
knn = KNeighborsClassifier()

knn  # 使用默认超参数

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

## 5. 训练模型

In [22]:
knn.fit(X_train,y_train)  # 模型的训练，需要训练集的特征 和 训练集的目标

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

## 6. 测试模型并评分

In [23]:
test_score = knn.score(X_test,y_test)  # 自动使用模型区预测，并且与真实值比较，来评估模型
print("测试得分: ",test_score)  # F1-score

测试得分:  0.9333333333333333


In [24]:
from sklearn.metrics import accuracy_score # 准确率  正确数量/样本数量
from sklearn.metrics import precision_score,recall_score  # 查准率，召回率
from sklearn.metrics import f1_score  # 综合得分     model.score()
from sklearn.metrics import classification_report  # 分类报告

真实值 = y_test
预测值 = knn.predict(X_test)

print(classification_report(真实值,预测值,target_names=iris.target_names))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      0.85      0.92        13
   virginica       0.82      1.00      0.90         9

   micro avg       0.93      0.93      0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



## 7. 模型的应用

In [25]:
# 预测一个数据 得到分类
# 问：有一朵鸢尾花，它的花瓣长2.1 花瓣宽1.2， 花萼长3，花萼宽2，请问它是什么种类的鸢尾花？
y_pred = knn.predict([[2.1,1.2,3,2]])
y_pred

array([1])

In [26]:
print(f"答：这是一朵{iris.target_names[knn.predict([[2.1,1.2,3,2]])[0]]}花。")

答：这是一朵versicolor花。
