In [1]:
import numpy as np

In [9]:
iris_liyuan = np.loadtxt('iris.csv',delimiter=',',dtype='object',comments='//',skiprows=1)
iris_liyuan[:10]

array([['1', '4.9', '3', '1.4', '0.2', 'setosa'],
       ['2', '4.7', '3.2', '1.3', '0.2', 'setosa'],
       ['3', '4.6', '3.1', '1.5', '0.2', 'setosa'],
       ['4', '5', '3.6', '1.4', '0.2', 'setosa'],
       ['5', '5.4', '3.9', '1.7', '0.4', 'setosa'],
       ['6', '4.6', '3.4', '1.4', '0.3', 'setosa'],
       ['7', '5', '3.4', '1.5', '0.2', 'setosa'],
       ['8', '4.4', '2.9', '1.4', '0.2', 'setosa'],
       ['9', '4.9', '3.1', '1.5', '0.1', 'setosa'],
       ['10', '5.4', '3.7', '1.5', '0.2', 'setosa']], dtype=object)

In [10]:
nr_liyuan = iris_liyuan[:,0].reshape(-1,3)
nr_liyuan[:10]

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9'],
       ['10', '11', '12'],
       ['13', '14', '15'],
       ['16', '17', '18'],
       ['19', '20', '21'],
       ['22', '23', '24'],
       ['25', '26', '27'],
       ['28', '29', '30']], dtype=object)

In [11]:
X_liyuan = iris_liyuan[:,1:5].astype(float)
X_liyuan[:10]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

In [5]:
np.mean(X_liyuan,axis = 0)

array([5.838     , 3.05066667, 3.758     , 1.19933333])

In [6]:
class_array = iris_liyuan[:,-1]
classifications = np.unique(class_array)
classifications

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
for i in classifications:
    print(i,np.sum(class_array == i))

setosa 50
versicolor 50
virginica 50


In [8]:
new_class_array = []
for i in class_array:
    if i == 'setosa':
        data = 0
    elif i == 'versicolor':
        data = 1
    elif i == 'virginica':
        data = 2
    new_class_array.append(data)

np.array(new_class_array)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])