# Numpy 数据获取

## 1 文本文件导入导出
```python
loadtxt
savetxt
```

In [1]:
# 导入numpy 模块
import numpy as np

In [2]:
# 创建一点数据
a = np.arange(100)
a.reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
a[:,1:5].astype(float)

array([[ 1.,  2.,  3.,  4.],
       [11., 12., 13., 14.],
       [21., 22., 23., 24.],
       [31., 32., 33., 34.],
       [41., 42., 43., 44.],
       [51., 52., 53., 54.],
       [61., 62., 63., 64.],
       [71., 72., 73., 74.],
       [81., 82., 83., 84.],
       [91., 92., 93., 94.]])

In [13]:
a.resize((10,10))

In [4]:
# 保存数据到文本文件中
np.savetxt(
    'a.txt',
    a,
    fmt='%02d',
    delimiter=',',
    header='a,b,c,d,e,f,g,h,i,j',
    footer='a,b,c,d,e,f,g,h,i,j',
)

In [5]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

- reshape() 改变形状，生成一个新的数组
- resize() 直接在原数据上改变形状，不生成新的数组，没有返回值

In [10]:
np.loadtxt(
    'a.csv',  # 文件名
    delimiter=';', # 列分隔符
    dtype='int32', # 数据类型
    skiprows=1,    # 跳过前1行(列头行)
    comments="//", # 注释行格式,//开头的为注释行
    max_rows=10,
    usecols=range(0,9,2),
)

array([[ 1,  3,  5,  7,  9],
       [10, 12, 14, 16, 18],
       [19, 21, 23, 25, 27],
       [28, 30, 32, 34, 36],
       [37, 39, 41, 43, 45],
       [46, 48, 50, 52, 54],
       [55, 57, 59, 61, 63],
       [64, 66, 68, 70, 72],
       [73, 75, 77, 79, 81]])

### 练习： 导入iris.csv文件，并计算每一列值得平均数

In [35]:
# 读取数据文件
data = np.loadtxt(
    'iris.csv',  # 文件名
    delimiter=',', # 列分隔符
    dtype='U', # 数据类型
    skiprows=1,    # 跳过前1行(列头行)
    comments="//", # 注释行格式,//开头的为注释行
)

# 将空字符串转换成数值字符
for i in range(data.shape[0]): # shape[0] 行数
    for j in range(data.shape[1]): # shape[1] 列数
        if data[i,j]=="":
            data[i,j]="0"

# 转换数据类型
data = data.astype("float")

# 统计
np.mean(data,axis=0) # axis=0 按列统计

array([7.21296296, 4.48518519, 5.15617284, 2.71049383, 2.53703704])

In [18]:
def convert_empty_to_zero(x):
    if x=="":
        return "0"
    
convert_empty_to_zero("")

'0'

In [36]:
data = np.loadtxt(
    'iris.csv',  # 文件名
    delimiter=',', # 列分隔符
    dtype='U', # 数据类型
    skiprows=1,    # 跳过前1行(列头行)
    comments="//", # 注释行格式,//开头的为注释行
)